import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import Header from "./components/Header";
import Layout from "./components/Layout";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "Shoping_mart",
    default: "Shoping Mart - A simple e-commerce website",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className="w-full bg-main-bg">
        <Layout>
          <Header />
          {children}
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
